# Generated by Django 4.1.6 on 2023-02-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stockdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.IntegerField(null=True)),
                ('joined_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tradedata',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('sname', models.CharField(max_length=200)),
                ('sprice', models.IntegerField()),
                ('sqty', models.IntegerField()),
            ],
            options={
                'db_table': 'dataa',
            },
        ),
    ]
