# Generated by Django 4.1.6 on 2023-02-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_rename_member_stockdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
