# Generated by Django 4.1.6 on 2023-02-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stockdata_joined_date_stockdata_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tradedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('sname', models.CharField(max_length=200)),
                ('sprice', models.IntegerField()),
                ('sqty', models.IntegerField()),
            ],
        ),
    ]
