# Generated by Django 4.1.6 on 2023-02-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_tradedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradedata',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
