# Generated by Django 4.1.6 on 2023-02-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_tradedata_code'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tradedata',
            table='dataa',
        ),
    ]
